### ISSUE TITLE
Presentation for Sunday

### ISSUE THREAD

**Issue by yuki-93** [Jugendhackt/wahl-p-aka#7]

**Comment by ghost** [comment]
https://pad.medialepfade.net/jhcgn2021-wahl-p-aka

**Comment by ghost** [comment]
- "Note" und Namen löschen
- API erklären
- Wann wird die nächste Folie angeklickt
- Punkte für den Ausblick

**Comment by e1mo** [comment]
TODO: Add a note about or reverse proxy cache setup.
